{{- if (eq .Values.deploymentType "individual") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRulesConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  alert-rules.json: |-
    {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRulesConfig.rules |  toJson  }}
{{- end }}