{{- if (eq .Values.deploymentType "individual") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.individual.metricAnomalyTaskManagerConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    queue.config {
      kafka {
        bootstrap.servers {{ .Values.individual.metricAnomalyTaskManagerConfig.queueConfig.bootstrapServers  | quote }}
        producer {
          schema.registry.url = {{ .Values.individual.metricAnomalyTaskManagerConfig.queueConfig.schemaRegistryUrl  | quote }}
          key.serializer = {{ .Values.individual.metricAnomalyTaskManagerConfig.queueConfig.producer.keySerializer  | quote }}
          value.serializer = {{ .Values.individual.metricAnomalyTaskManagerConfig.queueConfig.producer.valueSerializer  | quote }}
        }
      }
    }

    alertRuleSource {
      type =  {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.type  | quote }}
      {{- if eq "fs" .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.type }}
      fs {
        path = {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.fs.path | quote }}
      }
     {{- else }}
      dataStore {
        resourceName = {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.resourceName | quote }}
        resourceNamespace = {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.resourceNamespace | quote }}
        config.service {
          host = {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.host | quote }}
          port = {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.port | quote }}
        }
        tenantIds = {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.tenantIds }}
      }
      {{- end }}
    }
{{- end }}