apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metricAnomalyTaskManagerConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    queue.config {
      kafka = {
        bootstrap.servers = {{ .Values.metricAnomalyTaskManagerConfig.queueConfig.bootstrapServers }}
        producer {
          schema.registry.url = {{ .Values.metricAnomalyTaskManagerConfig.queueConfig.schemaRegistryUrl }}
          key.serializer= {{ .Values.metricAnomalyTaskManagerConfig.queueConfig.producer.keySerializer }}
          value.serializer= {{ .Values.metricAnomalyTaskManagerConfig.queueConfig.producer.valueSerializer }}
        }
      }
    }

    alertRuleSource {
      type =  {{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.type }}
      {{- if eq "fs" .Values.metricAnomalyTaskManagerConfig.alertRuleSource.type }}
      fs {
        path = {{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.fs.path | quote }}
      }
     {{- else }}
      dataStore {
        resourceName = {{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.resourceName | quote }}
        resourceNamespace = {{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.resourceNamespace | quote }}
        config.service {
          host={{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.host | quote }}
          port={{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.port | quote }}
        }
        tenantIds = {{ .Values.metricAnomalyTaskManagerConfig.alertRuleSource.dataStore.tenantIds }}
      }
      {{- end }}
    }
