{{- if (eq .Values.deploymentType "individual") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.individual.metricAnomalyTaskManagerConfig.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.individual.metricAnomalyTaskManagerConfig.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.individual.metricAnomalyTaskManagerConfig.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.individual.metricAnomalyTaskManagerConfig.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
      {{- with .Values.individual.metricAnomalyTaskManagerConfig.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/metric-anomaly-task-manager/application-config.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.individual.metricAnomalyTaskManagerConfig.containerAdminPort | quote }}
      {{- with .Values.individual.metricAnomalyTaskManagerConfig.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.individual.metricAnomalyTaskManagerConfig.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: service-config
          configMap:
            name: {{ .Values.individual.metricAnomalyTaskManagerConfig.name }}
        - name: log4j-config
          configMap:
            name: {{ .Values.individual.metricAnomalyTaskManagerConfig.logConfig.name }}
        - name: alert-rules-config
          configMap:
            name: {{ .Values.individual.metricAnomalyTaskManagerConfig.alertRulesConfig.name }}
    {{- with .Values.individual.metricAnomalyTaskManagerConfig.nodeLabels }}
      nodeSelector:
      {{- toYaml . | nindent 8}}
    {{- end }}
      containers:
        - name: {{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}
          image: "{{ include "service.image" (dict "name" .Values.individual.metricAnomalyTaskManagerConfig "context" . ) }}"
          imagePullPolicy: {{ .Values.individual.metricAnomalyTaskManagerConfig.image.pullPolicy }}
          ports:
            - name: admin-port
              containerPort: {{ .Values.individual.metricAnomalyTaskManagerConfig.containerAdminPort }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "{{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}"
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}/log/log4j2.properties"
            - name: JAVA_OPTS
              value: {{ .Values.individual.metricAnomalyTaskManagerConfig.javaOpts | quote }}
            - name: ALERT_RULES_PATH
              value: "/var/{{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}/rules/alert-rules.json"
          volumeMounts:
            - name: service-config
              mountPath: /app/resources/configs/{{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}/application.conf
              subPath: application.conf
            - name: log4j-config
              mountPath: /var/{{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}/log
            - name: alert-rules-config
              mountPath: /var/{{ .Values.individual.metricAnomalyTaskManagerConfig.deploymentName }}/rules/alert-rules.json
              subPath: alert-rules.json
          livenessProbe:
            initialDelaySeconds: {{ int .Values.individual.metricAnomalyTaskManagerConfig.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.individual.metricAnomalyTaskManagerConfig.livenessProbe.periodSeconds }}
            tcpSocket:
              port: admin-port
          readinessProbe:
            initialDelaySeconds: {{ int .Values.individual.metricAnomalyTaskManagerConfig.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.individual.metricAnomalyTaskManagerConfig.readinessProbe.periodSeconds }}
            failureThreshold: {{ int .Values.individual.metricAnomalyTaskManagerConfig.readinessProbe.failureThreshold }}
            httpGet:
              path: /health
              port: {{ .Values.individual.metricAnomalyTaskManagerConfig.containerAdminPort }}
          resources:
            {{- toYaml .Values.individual.metricAnomalyTaskManagerConfig.resources | nindent 12 }}
{{- end }}