apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.notificationServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    queue.config {
      kafka {
        bootstrap.servers = {{ .Values.notificationServiceConfig.queueConfig.bootstrapServers }}
        consumer {
          schema.registry.url = {{ .Values.notificationServiceConfig.queueConfig.schemaRegistryUrl }}
          key.deserializer= {{ .Values.notificationServiceConfig.queueConfig.consumer.keyDeserializer }}
          value.deserializer= {{ .Values.notificationServiceConfig.queueConfig.consumer.valueDeserializer }}
        }
      }
    }