{{- if and (eq .Values.deploymentType "individual") .Values.individual.notificationServiceConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.individual.notificationServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    queue.config {
      kafka {
        bootstrap.servers = {{ .Values.individual.notificationServiceConfig.queueConfig.bootstrapServers | quote }}
        consumer {
          schema.registry.url = {{ .Values.individual.notificationServiceConfig.queueConfig.schemaRegistryUrl | quote }}
          key.deserializer = {{ .Values.individual.notificationServiceConfig.queueConfig.consumer.keyDeserializer | quote }}
          value.deserializer = {{ .Values.individual.notificationServiceConfig.queueConfig.consumer.valueDeserializer | quote }}
        }
      }
    }
{{- end }}