{{- if and (eq .Values.deploymentType "individual") .Values.individual.notificationServiceConfig.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.individual.notificationServiceConfig.deploymentName }}
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.individual.notificationServiceConfig.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.individual.notificationServiceConfig.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.individual.notificationServiceConfig.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.individual.notificationServiceConfig.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
      {{- with .Values.individual.notificationServiceConfig.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/notification-service/application-config.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.individual.notificationServiceConfig.containerAdminPort | quote }}
      {{- with .Values.individual.notificationServiceConfig.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.individual.notificationServiceConfig.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: service-config
          configMap:
            name: {{ .Values.individual.notificationServiceConfig.name }}
        - name: log4j-config
          configMap:
            name: {{ .Values.individual.notificationServiceConfig.logConfig.name }}
        - name: notification-channels-config
          configMap:
            name: {{ .Values.individual.notificationServiceConfig.notificationChannelsConfig.name }}
    {{- with .Values.individual.notificationServiceConfig.nodeLabels }}
      nodeSelector:
      {{- toYaml . | nindent 8}}
    {{- end }}
      containers:
        - name: {{ .Values.individual.notificationServiceConfig.deploymentName }}
          image: "{{ include "service.image" (dict "name" .Values.individual.notificationServiceConfig "context" . ) }}"
          imagePullPolicy: {{ .Values.individual.notificationServiceConfig.image.pullPolicy }}
          ports:
            - name: admin-port
              containerPort: {{ .Values.individual.notificationServiceConfig.containerAdminPort }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "{{ .Values.individual.notificationServiceConfig.deploymentName }}"
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Values.individual.notificationServiceConfig.deploymentName }}/log/log4j2.properties"
            - name: JAVA_OPTS
              value: {{ .Values.individual.notificationServiceConfig.javaOpts | quote }}
            - name: NOTIFICATION_CHANNELS_PATH
              value: "/var/{{ .Values.individual.notificationServiceConfig.deploymentName }}/rules/notification-channels.json"
          volumeMounts:
            - name: service-config
              mountPath: /app/resources/configs/{{ .Values.individual.notificationServiceConfig.deploymentName }}/application.conf
              subPath: application.conf
            - name: log4j-config
              mountPath: /var/{{ .Values.individual.notificationServiceConfig.deploymentName }}/log
            - name: notification-channels-config
              mountPath: /var/{{ .Chart.Name }}/rules/notification-channels.json
              subPath: notification-channels.json
          livenessProbe:
            initialDelaySeconds: {{ int .Values.individual.notificationServiceConfig.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.individual.notificationServiceConfig.livenessProbe.periodSeconds }}
            tcpSocket:
              port: admin-port
          readinessProbe:
            initialDelaySeconds: {{ int .Values.individual.notificationServiceConfig.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.individual.notificationServiceConfig.readinessProbe.periodSeconds }}
            failureThreshold: {{ int .Values.individual.notificationServiceConfig.readinessProbe.failureThreshold }}
            httpGet:
              path: /health
              port: {{ .Values.individual.notificationServiceConfig.containerAdminPort }}
          resources:
            {{- toYaml .Values.individual.notificationServiceConfig.resources | nindent 12 }}
{{- end }}