{{- if and (eq .Values.deploymentType "individual" ) .Values.individual.notificationServiceConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.individual.notificationServiceConfig.notificationChannelsConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  notification-channels.json: |-
    {{ .Values.individual.notificationServiceConfig.notificationChannelsConfig.channels |  toJson  }}
{{- end }}