# Default values for the helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Note about Namespace
# --------------------
# It is deliberately left out here and using the helm -n or --namespace flag you can deploy your resources to the same
# namespace as the release. If you leave it out, your resources will be deployed to the default namespace.
# Also, not that the namespace you are deploying to should already exist otherwise the helm command will fail.
# You can always specify a different namespace for a resource by setting it directly in it's yaml file or
# making it configurable by defining it in this file.

###########
# Deployment
###########
replicaCount: 1
maxUnavailable: 0

image:
  repository: hypertrace/metric-anomaly-task-manager
  pullPolicy: IfNotPresent
  tagOverride: ""

imagePullSecrets: []

nodeLabels: {}

# This is defined in resources/configs/metric-anomaly-task-manager/application.conf as service.admin.port
containerAdminPort: 8099

javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0 -XX:MaxDirectMemorySize=128M"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 15
  failureThreshold: 5

resources:
  requests:
    cpu: 0.1
    memory: 1024Mi
  limits:
    cpu: 0.2
    memory: 1024Mi

deploymentLabels:
  app: metric-anomaly-task-manager

podLabels:
  app: metric-anomaly-task-manager

podAnnotations: {}

# The Deployment Selector match labels are different from the pod labels. Note that they should be a subset of the pod
# labels. You append new labels to them but cannot remove labels. If you remove or modify the labels you will need to
# delete the existing deployment bearing the same name and then redeploy. This is the reason why they are separated from
# the pod labels. You can add and remove pod labels without having an effect on the deployment.
# Also, please use "apiVersion: apps/v1" instead of the deprecated "apiVersion: extensions/v1beta1" for the deployment
# apiVersion in the yaml file.
deploymentSelectorMatchLabels:
  app: metric-anomaly-task-manager

serviceSelectorLabels:
  app: metric-anomaly-task-manager

###########
# Config Maps
###########
metricAnomalyTaskManagerConfig:
  name: metric-anomaly-task-manager-config
  queueConfig:
    outputTopic: alert-tasks
    bootstrapServers: bootstrap

logConfig:
  name: metric-anomaly-task-manager-log-appender-config
  monitorInterval: 30
  rootLogger:
    level: INFO
  appender:
    rolling:
      enabled: false

alertRulesConfig:
  name: metric-anomaly-task-manager-alert-rules-config
  rules:
    [
      {
        "id": "notification_rule_1",
        "ruleName": "high_avg_latency",
        "description": "Alert for high avg latency of payment service",
        "eventConditionId": "event_condition_1",
        "eventConditionType": "metricAnomalyEventCondition",
        "channelId": "channel-id-1",
        "eventCondition": {
          "metricSelection": {
            "metricAttribute": {
              "key": "duration",
              "scope": "SERVICE"
            },
            "metricAggregationFunction": "METRIC_AGGREGATION_FUNCTION_TYPE_AVG",
            "metricAggregationInterval": "PT15S",
            "filter": {
              "leafFilter": {
                "lhsExpression": {
                  "attribute": {
                    "key": "name",
                    "scope": "SERVICE"
                  }
                },
                "valueOperator": "VALUE_OPERATOR_EQ",
                "rhsExpression": {
                  "stringValue": "customer"
                }
              }
            }
          },
          "violationCondition": [ {
            "staticThresholdCondition": {
              "operator": "STATIC_THRESHOLD_OPERATOR_GT",
              "value": 5.0,
              "minimumViolationDuration": "PT5M",
              "severity": "SEVERITY_CRITICAL"
            }
          } ]
        }
      }
    ]