apiVersion: v2
name: notification-service
description: Alerting

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version. The "helm package" command will take care of setting this.
# A new chart will be created for each new version of the service.
version: 0.1.0
