apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metricAnomalyTaskManagerConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    queue.config {
      kafka = {
        topic = {{ .Values.metricAnomalyTaskManagerConfig.queueConfig.outputTopic }}
        bootstrap.servers = {{ .Values.metricAnomalyTaskManagerConfig.queueConfig.bootstrapServers }}
      }
    }