{{- if .Values.hypertraceAlertEngine.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hypertraceAlertEngineConfig.alertRulesConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  alert-rules.json: |-
    {{ .Values.hypertraceAlertEngineConfig.alertRulesConfig.rules |  toJson  }}
{{- end }}