{{- if (eq .Values.deploymentType "aggregated") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.aggregated.hypertraceAlertEngineConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    query.service.config {
      host = {{ .Values.aggregated.hypertraceAlertEngineConfig.queryService.host }}
      port = {{ .Values.aggregated.hypertraceAlertEngineConfig.queryService.port }}
    }

    attributes.service.config {
      host = {{ .Values.aggregated.hypertraceAlertEngineConfig.attributeService.host }}
      port = {{ .Values.aggregated.hypertraceAlertEngineConfig.attributeService.port }}
    }
{{- end }}