{{- if (eq .Values.deploymentType "aggregated") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.aggregated.hypertraceAlertEngineConfig.notificationChannelsConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  notification-channels.json: |-
    {{ .Values.aggregated.hypertraceAlertEngineConfig.notificationChannelsConfig.channels |  toJson  }}
{{- end }}