{{- if .Values.hypertraceAlertEngine.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hypertraceAlertEngineConfig.notificationChannelsConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  notification-channels.json: |-
    {{ .Values.hypertraceAlertEngineConfig.notificationChannelsConfig.channels |  toJson  }}
{{- end }}