{{- if (eq .Values.deploymentType "individual") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.individual.metricAnomalyDetectorConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    query.service.config {
      host = {{ .Values.individual.metricAnomalyDetectorConfig.queryService.host | quote }}
      port = {{ .Values.individual.metricAnomalyDetectorConfig.queryService.port | quote }}
    }

    attributes.service.config {
      host = {{ .Values.individual.metricAnomalyDetectorConfig.attributeService.host | quote }}
      port = {{ .Values.individual.metricAnomalyDetectorConfig.attributeService.port | quote }}
    }

    queue.config {
      kafka {
        bootstrap.servers = {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.bootstrapServers | quote }}
        consumer {
          schema.registry.url = {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.schemaRegistryUrl | quote }}
          key.deserializer= {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.consumer.keyDeserializer | quote }}
          value.deserializer= {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.consumer.valueDeserializer | quote }}
        }
        producer {
          schema.registry.url = {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.schemaRegistryUrl | quote }}
          key.serializer= {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.producer.keySerializer | quote }}
          value.serializer= {{ .Values.individual.metricAnomalyDetectorConfig.queueConfig.producer.valueSerializer | quote }}
        }
      }
    }
{{- end }}