apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metricAnomalyDetectorConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    query.service.config = {
      host = {{ .Values.metricAnomalyDetectorConfig.queryService.host }}
      port = {{ .Values.metricAnomalyDetectorConfig.queryService.port }}
    }

    attributes.service.config = {
      host = {{ .Values.metricAnomalyDetectorConfig.attributeService.host }}
      port = {{ .Values.metricAnomalyDetectorConfig.attributeService.port }}
    }

    queue.config {
      kafka = {
        bootstrap.servers = {{ .Values.metricAnomalyDetectorConfig.queueConfig.bootstrapServers }}
        consumer {
          topic = {{ .Values.metricAnomalyDetectorConfig.queueConfig.inputTopic }}
        }
        producer {
          topic = {{ .Values.metricAnomalyDetectorConfig.queueConfig.outputTopic }}
        }
      }
    }